[project]
authors = ["Scott Henderson <scottyhq@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "3D_CRS_Transformation_Resources"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
gdal = ">=3.10.0,<4"
ipython = ">=8.31.0,<9"
geopandas = ">=1.0.1,<2"
xarray = ">=2024.11.0,<2025"
rioxarray = ">=0.17.0,<0.18"
matplotlib = ">=3.10.0,<4"
ipykernel = ">=6.29.5,<7"
dask = ">=2024.12.1,<2025"
xvec = ">=0.3.1,<0.4"
